# wrangler.toml
name = "movietracker"
main = "./.output/server/index.mjs"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./.output/public"

[[ d1_databases ]]
binding = "DB"
database_name = "movietracker"
database_id = "8e4c24eb-3c24-4da6-b630-958be192ec45"
migrations_dir = "drizzle"