# wrangler.toml
name = "movietracker"
compatibility_date = "2025-08-26"
main = "./src/api/index.jsx"
compatibility_flags = [ "nodejs_compat" ]

[[ d1_databases ]]
binding = "DB"
database_name = "movietracker"
database_id = "8e4c24eb-3c24-4da6-b630-958be192ec45"
migrations_dir = "drizzle"